before:
  hooks:
    - go mod tidy
builds:
  - binary: bin/godraft
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.Version={{.Version}}